name: Build VoidLink IPA (Integration)

on:
  # 1. 当向 Integration 分支推送代码时自动触发
  push:
    branches: [ "Integration" ] 
  
  # 2. 允许手动点击按钮触发
  workflow_dispatch:

jobs:
  build:
    name: Build VoidLink IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: "git submodule update --init --recursive"

      - name: Build VoidLink
        # 注意：这里保持了你原有的无签名配置
        run: |
          xcodebuild -verbose -scheme VoidLink -sdk iphoneos -configuration Debug archive -archivePath $PWD/build/VoidLink.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
          mkdir -p ./build/IPA && mkdir -p ./build/IPA/Payload
          cp -r ./build/VoidLink.xcarchive/Products/Applications/VoidLink.app ./build/IPA/Payload/VoidLink.app
          cd ./build/IPA && zip -r ../../build/VoidLink.ipa ./Payload/* && cd ../..

      - name: Upload VoidLink IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VoidLink-Integration.ipa
          path: build/VoidLink.ipa
